---
title: "Two Parameters"
author: "Andrew"
format: html
execute: 
  echo: false
---


```{r}
#| message: FALSE 

library(tidyverse)
library(primer.data)
library(brms)
library(tidybayes)
library(gtsummary)

```

```{r}
#| cache: TRUE
ch5 <- nhanes |>
  filter(sex == "Male", age >= 18) |>
  select(height) |>
  drop_na()

fit_male_height <- brm(
    formula = height ~ 1,
    data = ch5,
    family = gaussian(),
    silent = 2,
    refresh = 0,
    seed = 12)

```

```{r}
nhanes |>
  filter(sex == "Male",
         age >= 18) |>
  select(height) |>
  drop_na() |>
  ggplot(aes(x=height)) +
    geom_histogram(bins=50) +
    labs(title = "Make Adult Height in the US in 2010",
         caption = "Souirce: National Health and Nutrition Examination Survey",
         x = "Height (cm)",
         y = "Count")
```

```{r}
#| label: plot
ndata <- tibble(.rows = 1)
fit_male_height |>
  add_predicted_draws(newdata = ndata) |>
  ggplot(aes(x=.prediction)) +
    geom_histogram(aes(y=after_stat(count / sum(count))), bins=100) +
    labs(title = "Posterior for Height of Random Male",
         subtitle = "Uncertainty for a single individual is much greater than for the expected value",
         x = "Height (cm)",
         y = "Probability",
         caption = "Data source: NAHNES") +
    scale_x_continuous(labels = scales::number_format()) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1))

```

Using The nhanes data set from the National Health and Nutrition Examination Survey of 10,000 individuals we will create a model of height for adult men.  Unfortunately this data is over 10 years old.  We modeled height using an intercept-only regression.  There is approximately a 30% chance that the next man we meet will be taller than 180 cm.


```{r}
tbl_regression(fit_male_height, intercept=TRUE)

```


```{r}
fit_male_height |>
  add_predicted_draws(newdata = ndata) |>
  mutate(tall = if_else(.prediction > 180, TRUE, FALSE)) |>
  summarize(odds = mean(tall))

```

